// Copy-paste the components .min codes that you will use. And just import one file (components.js)

// NOTE: You don't have to use this compression technique, but it can be useful for larger projects.

// Badget:
"use strict";const Badget=function(t={}){const e={target:null,type:"number",border:0,color:"transparent",width:"auto",height:"auto"};if("get"==t)return e;const o=startObject();return o.props(e,t),o.setIconFile=function(t){o.iconFile=t,o.icoLogo.load(t)},o.setMotion("opacity 0.2s"),o.target.containerBox.add(o),o.elem.style.overflow="visible",o.circleBox=startFlexBox(0,0,40,40,{color:"gold",position:"relative",border:3,borderColor:"rgba(0, 0, 0, 0.9)"}),that.round=that.width,that.elem.style.overflow="visible",o.lblText=Label({text:"42",fontSize:12,textColor:"rgba(0, 0, 0, 0.9)"}),endFlexBox(),o.on("click",(function(){})),o.top=o.target.top-12,o.left=o.target.left+o.target.width-o.circleBox.width+12,endObject(o)};

// Tooltip:
"use strict";const Tooltip=function(l={}){const o=startObject();o.props({target:null,hintText:"",hintPosition:"top",lbl_fontSize:12,lbl_spaceX:8,lbl_spaceY:3,lbl_color:"rgba(255, 255, 255, 0.90)",lbl_textColor:"rgba(0, 0, 0, 0.85)",lbl_round:3,lbl_border:1,lbl_borderColor:"rgba(0, 0, 0, 0.9)",visible:0},l);let t=null,n=null,i=null;return o.remove=function(){t(),n(),window.lblHint&&(window.lblHint.remove(),window.lblHint=null),i(),o.elem.remove()},o.setHintText=function(l){o.hintText=l,window.lblHint&&(window.lblHint.text=l)},o.setLbl_color=function(l){o.lbl_color=l,window.lblHint||(window.lblHint.color=o.lbl_color)},t=o.target.on("mouseover",(function(){window.lblHint||(window.lblHint=Label({fontSize:o.lbl_fontSize,spaceX:o.lbl_spaceX,spaceY:o.lbl_spaceY,color:o.lbl_color,textColor:o.lbl_textColor,round:o.lbl_round,border:o.lbl_border,borderColor:o.lbl_borderColor}),page.add(that),that.text=o.hintText)})),n=o.target.on("mousemove",(function(){window.lblHint&&function(){const l=window.event,t=l.clientX,n=l.clientY;switch(o.mouseX=withPageZoom(t),o.mouseY=withPageZoom(n),o.hintPosition){case"top":window.lblHint.top=o.mouseY-window.lblHint.height-12,window.lblHint.left=o.mouseX-window.lblHint.width/2;break;case"bottom":window.lblHint.top=o.mouseY+window.lblHint.height+8,window.lblHint.left=o.mouseX-window.lblHint.width/2;break;case"left":window.lblHint.top=o.mouseY-window.lblHint.height/2,window.lblHint.left=o.mouseX-window.lblHint.width-25;break;case"right":window.lblHint.top=o.mouseY-window.lblHint.height/2,window.lblHint.left=o.mouseX+25;break}}(o.hintPosition)})),i=o.target.on("mouseout",(function(){window.lblHint&&(window.lblHint.remove(),window.lblHint=null)})),o.target.clickable=1,endObject(o)};

// Tinytable:
"use strict";const TinyTableDefaults={columnHeaders:[],columnWidths:[],dataRows:[],headerBackgroundColor:"#141414",headerTextColor:"white",headerBorderColor:"#141414",headerFontSize:18,borderWidth:2,borderRadius:4,borderColor:"#141414",bodyHeight:"auto",bodyBackgroundColor:"white",cellFontSize:16,cellTextColor:"rgba(0, 0, 0, 0.9)",rowHoverBackgroundColor:"whitesmoke",rowHoverBorderColor:"rgba(0, 0, 0, 0.2)",rowHoverBorderWidth:1,onCellRender:function(o){}},TinyTable=function(o={}){const e=startObject();e.props(TinyTableDefaults,o),e.round=e.borderRadius,e.color="transparent",e.width="auto",e.height="auto",e.titleBox=startFlexBox({height:"auto",color:e.headerBorderColor,justifyContent:"flex-start",gap:"1px"}),that.position="relative";for(let o=0;o<e.columnHeaders.length;o++)Label({text:e.columnHeaders[o],width:e.columnWidths[o],spaceX:8,spaceY:8,color:e.headerBackgroundColor,textColor:e.headerTextColor,round:0,fontSize:e.headerFontSize}),that.elem.style.whiteSpace="nowrap",that.elem.style.textOverflow="ellipsis";endFlexBox(),e.contentGroup=startBox({height:e.bodyHeight,width:"auto",color:e.bodyBackgroundColor}),that.position="relative",that.elem.style.paddingTop="10px",that.elem.style.paddingBottom="10px","auto"!==e.bodyHeight&&(e.contentGroup.scrollY=1);const t=Box(0,0,{color:e.rowHoverBackgroundColor,border:e.rowHoverBorderWidth,borderColor:e.rowHoverBorderColor,opacity:0});for(let o=0;o<e.dataRows.length;o++){startFlexBox({height:"auto",color:"transparent",justifyContent:"flex-start",gap:"1px"}),that.position="relative",that.elem.style.cursor="pointer";const r=that;r.on("mouseover",(function(){t.opacity=1,t.width=r.width,t.height=r.height,t.top=r.top,t.left=0})),r.on("mouseout",(function(){t.opacity=0}));for(let t=0;t<e.dataRows[o].length;t++)Label({text:e.dataRows[o][t],width:e.columnWidths[t],spaceX:8,spaceY:4,color:"transparent",fontSize:e.cellFontSize,round:0,textColor:e.cellTextColor}),that.elem.style.whiteSpace="nowrap",that.elem.style.textOverflow="ellipsis",that.lineCount=o,that.index=t,e.onCellRender(that);endFlexBox()}return endBox(),e.coverBox=Box(0,0,"100%","100%",{color:"transparent",border:e.borderWidth,borderColor:e.borderColor,round:e.borderRadius}),endObject(e)};