/* Bismillah */

/*

basic.js Handbook Website - Texts - v26.09

- Sitedeki arayüz yazıları ve "Hızlı başlangıç" bölümü. İki dilde de aynı anahtarlar bulunmalıdır.
  Diğer bölümlerin metni __handbook klasöründeki Markdown dosyalarından gelir.
- The interface copy and the "Quick start" chapter. Both languages must have the same keys.

Developer: Bugra Ozden
Email: bugra.ozden@gmail.com

*/

"use strict";

const TEXTS = {

    en: {
        htmlLang: "en",
        pageTitle: "basic.js Handbook – Build web UIs with plain JavaScript",
        pageDescription: "Learn basic.js step by step: objects, layout, events, motion. Every example runs in the page and can be edited.",
        languageButton: "TR",
        languageHint: "Türkçe",

        // HEADER
        searchPlaceholder: "Search the handbook",
        searchHint: "Press / to search",
        searchEmpty: "Nothing found for \"{query}\"",
        searchKeys: "↑ ↓ to move · Enter to open · Esc to close",
        menu: "Menu",
        closeMenu: "Close the menu",
        navComponents: "Components",
        navGithub: "GitHub",

        // SIDEBAR GROUPS
        groups: {
            start: "Getting started",
            objects: "Objects",
            layout: "Layout and page",
            more: "Motion and more",
        },

        // ARTICLE
        onThisPage: "On this page",
        previous: "Previous",
        next: "Next",
        loading: "Loading the handbook…",
        loadError: "The handbook could not be loaded.",
        fileProtocol: "The handbook files are read with fetch, which does not work when the page is opened as a file (file://). Open this folder with a web server, for example VS Code Live Server.",
        retry: "Try again",

        // CODE BLOCKS
        run: "Run",
        runAgain: "Run again",
        copy: "Copy",
        copied: "The code is copied.",
        copyFailed: "The code could not be copied.",
        reset: "Reset",
        result: "Result",
        console: "Console",
        editHint: "You can edit the code. Ctrl + Enter runs it.",
        snippetNote: "Some examples are parts of a longer example; they may need the objects created in the text before them.",

        // FOOTER
        footerText: "basic.js is open source (Apache 2.0). This site is built with basic.js and reads the handbook from its Markdown files.",

        // QUICK START (Markdown)
        quickStart: [
            "# Quick Start",
            "",
            "A basic.js page is a plain `.htm` file. It loads the library, and one function draws the whole screen: there is no HTML markup in the `<body>` and no CSS file to write.",
            "",
            "---",
            "",
            "## 1. Create the page",
            "",
            "Put the `basic` folder next to your page and create `index.htm`:",
            "",
            "```html",
            "<!DOCTYPE html>",
            "<html lang=\"en\">",
            "<head>",
            "    <title>My App</title>",
            "    <meta charset=\"UTF-8\">",
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
            "",
            "    <!-- LIBRARY FILES -->",
            "    <link rel=\"stylesheet\" href=\"basic/basic.min.css\">",
            "    <script src=\"basic/basic.min.js\"></script>",
            "",
            "    <script>",
            "        const start = function () {",
            "            // Your code",
            "        };",
            "    </script>",
            "</head>",
            "<body></body>",
            "</html>",
            "```",
            "",
            "---",
            "",
            "## 2. Write start()",
            "",
            "When the page is loaded, basic.js creates the `page` object and calls your `start()` function. Every object you create in it is added to the screen.",
            "",
            "Press **Run** to see this example, then change the code and run it again:",
            "",
            "```javascript",
            "let count = 0;",
            "",
            "const start = function () {",
            "",
            "    page.color = \"whitesmoke\";",
            "",
            "    // GROUP: Everything in the middle, one under the other",
            "    VGroup({ align: \"center\", gap: 16 });",
            "",
            "        Label({ text: \"Hello basic.js\", fontSize: 28 });",
            "",
            "        const btn = Button({ text: \"Click me\", width: 180 });",
            "        btn.on(\"click\", function (self) {",
            "            count++;",
            "            self.text = \"Clicked: \" + count;",
            "        });",
            "",
            "    endGroup();",
            "",
            "};",
            "```",
            "",
            "---",
            "",
            "## 3. Open it",
            "",
            "Open the file in a browser. In VS Code, the **Live Server** extension opens it and reloads it every time you save.",
            "",
            "---",
            "",
            "## The ideas to remember",
            "",
            "- **Objects:** `Box`, `Label`, `Button`, `Input` and `Icon`. Positions come first `(left, top, width, height)`, the settings object comes last. See [Box](#/box).",
            "- **that:** the object created last. `that.color = \"red\"` styles it right after it is created. See [Common properties](#/common-properties).",
            "- **Containers:** objects created between `startBox()` and `endBox()`, or between `HGroup()` / `VGroup()` and `endGroup()`, go inside that box. Every start needs its end. See [Autolayout](#/autolayout).",
            "- **Only a Box holds objects:** a `Button`, `Label`, `Input` or `Icon` can not have children.",
            "- **The page never scrolls:** put long content in a full screen Box with `scrollY: 1`. See [Page](#/page).",
            "- **Events:** `obj.on(\"click\", function (self, event) {})`. See [Common properties](#/common-properties).",
            "- **Motion:** `obj.setMotion(\"left 0.3s\")`, then change `left`. See [Motion](#/motion).",
        ].join("\n"),
    },

    tr: {
        htmlLang: "tr",
        pageTitle: "basic.js El Kitabı – Saf JavaScript ile web arayüzleri",
        pageDescription: "basic.js'i adım adım öğrenin: nesneler, yerleşim, olaylar, hareket. Her örnek sayfanın içinde çalışır ve düzenlenebilir.",
        languageButton: "EN",
        languageHint: "English",

        // HEADER
        searchPlaceholder: "El kitabında ara",
        searchHint: "Aramak için / tuşuna basın",
        searchEmpty: "\"{query}\" için bir sonuç yok",
        searchKeys: "↑ ↓ ile gezin · Enter ile açın · Esc ile kapatın",
        menu: "Menü",
        closeMenu: "Menüyü kapat",
        navComponents: "Bileşenler",
        navGithub: "GitHub",

        // SIDEBAR GROUPS
        groups: {
            start: "Başlangıç",
            objects: "Nesneler",
            layout: "Yerleşim ve sayfa",
            more: "Hareket ve diğerleri",
        },

        // ARTICLE
        onThisPage: "Bu sayfada",
        previous: "Önceki",
        next: "Sonraki",
        loading: "El kitabı yükleniyor…",
        loadError: "El kitabı yüklenemedi.",
        fileProtocol: "El kitabı dosyaları fetch ile okunur; sayfa dosya olarak (file://) açıldığında bu çalışmaz. Bu klasörü bir web sunucusu ile açın, örneğin VS Code Live Server.",
        retry: "Tekrar dene",

        // CODE BLOCKS
        run: "Çalıştır",
        runAgain: "Tekrar çalıştır",
        copy: "Kopyala",
        copied: "Kod kopyalandı.",
        copyFailed: "Kod kopyalanamadı.",
        reset: "Sıfırla",
        result: "Sonuç",
        console: "Konsol",
        editHint: "Kodu değiştirebilirsiniz. Ctrl + Enter çalıştırır.",
        snippetNote: "Bazı örnekler daha uzun bir örneğin parçasıdır; metinde daha önce oluşturulan nesnelere ihtiyaç duyabilir.",

        // FOOTER
        footerText: "basic.js açık kaynaktır (Apache 2.0). Bu site basic.js ile yapılmıştır ve el kitabını Markdown dosyalarından okur.",

        // QUICK START (Markdown)
        quickStart: [
            "# Hızlı Başlangıç",
            "",
            "Bir basic.js sayfası sade bir `.htm` dosyasıdır. Kütüphaneyi yükler ve bütün ekranı tek bir fonksiyon çizer: `<body>` içine HTML etiketi yazılmaz, CSS dosyası yoktur.",
            "",
            "---",
            "",
            "## 1. Sayfayı oluşturun",
            "",
            "`basic` klasörünü sayfanızın yanına koyun ve `index.htm` dosyasını oluşturun:",
            "",
            "```html",
            "<!DOCTYPE html>",
            "<html lang=\"tr\">",
            "<head>",
            "    <title>Uygulamam</title>",
            "    <meta charset=\"UTF-8\">",
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
            "",
            "    <!-- LIBRARY FILES -->",
            "    <link rel=\"stylesheet\" href=\"basic/basic.min.css\">",
            "    <script src=\"basic/basic.min.js\"></script>",
            "",
            "    <script>",
            "        const start = function () {",
            "            // Kodunuz",
            "        };",
            "    </script>",
            "</head>",
            "<body></body>",
            "</html>",
            "```",
            "",
            "---",
            "",
            "## 2. start() fonksiyonunu yazın",
            "",
            "Sayfa yüklenince basic.js, `page` nesnesini oluşturur ve sizin `start()` fonksiyonunuzu çağırır. Onun içinde oluşturduğunuz her nesne ekrana eklenir.",
            "",
            "Örneği görmek için **Çalıştır** düğmesine basın, sonra kodu değiştirip tekrar çalıştırın:",
            "",
            "```javascript",
            "let count = 0;",
            "",
            "const start = function () {",
            "",
            "    page.color = \"whitesmoke\";",
            "",
            "    // GROUP: Her şey ortada, alt alta",
            "    VGroup({ align: \"center\", gap: 16 });",
            "",
            "        Label({ text: \"Merhaba basic.js\", fontSize: 28 });",
            "",
            "        const btn = Button({ text: \"Bana tıkla\", width: 180 });",
            "        btn.on(\"click\", function (self) {",
            "            count++;",
            "            self.text = \"Tıklandı: \" + count;",
            "        });",
            "",
            "    endGroup();",
            "",
            "};",
            "```",
            "",
            "---",
            "",
            "## 3. Açın",
            "",
            "Dosyayı bir tarayıcıda açın. VS Code'da **Live Server** eklentisi sayfayı açar ve her kaydedişte yeniler.",
            "",
            "---",
            "",
            "## Akılda tutulacaklar",
            "",
            "- **Nesneler:** `Box`, `Label`, `Button`, `Input` ve `Icon`. Önce konum gelir `(left, top, width, height)`, ayar nesnesi en sondadır. Bkz. [Box](#/box).",
            "- **that:** en son oluşturulan nesne. `that.color = \"red\"` onu oluşturulduğu anda biçimlendirir. Bkz. [Ortak özellikler](#/common-properties).",
            "- **Kapsayıcılar:** `startBox()` ile `endBox()` arasında, ya da `HGroup()` / `VGroup()` ile `endGroup()` arasında oluşturulan nesneler o kutunun içine girer. Her start'ın bir end'i olmalı. Bkz. [Autolayout](#/autolayout).",
            "- **Sadece Box nesne tutar:** `Button`, `Label`, `Input` ve `Icon` içine nesne alamaz.",
            "- **Sayfa kaymaz:** uzun içeriği `scrollY: 1` verilmiş tam ekran bir Box içine koyun. Bkz. [Page](#/page).",
            "- **Olaylar:** `obj.on(\"click\", function (self, event) {})`. Bkz. [Ortak özellikler](#/common-properties).",
            "- **Hareket:** `obj.setMotion(\"left 0.3s\")`, sonra `left` değerini değiştirin. Bkz. [Hareket](#/motion).",
        ].join("\n"),
    },

};
