create table public."contactTable" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  first_name character varying null,
  last_name character varying null,
  email character varying null,
  phone character varying null,
  subject character varying null,
  message text null,
  constraint contactTable_pkey primary key (id)
) TABLESPACE pg_default;